services:

    node:
        image: node:alpine3.20
        ports:
          - "81:81"
        networks:
          - frontend
          - backend
        working_dir: /home/node/app
        env_file: "env"
        volumes:
          - ./node/:/home/node/app/:ro
        command: "npm start"
        depends_on:
          - db
        restart: always

    nginx:
        depends_on:
          - node
        image: nginx
        ports:
          - "80:80"
          - "443:443"
        networks:
          - frontend
          - backend
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf:rw
          - ./letsencrypt/:/etc/nginx/certificates/:rw
    
    db:
        image: mysql
        restart: always
        env_file: "env"   
        volumes:
          - database:/var/lib/mysql/
        networks:
          - backend
    pma:
        image: phpmyadmin
        restart: always
        depends_on:
          - db
        networks:
          - frontend
          - backend
        env_file: "env"
        ports:
          - "8080:80"
        expose:
          - 8080

networks:
    frontend:
    backend:

volumes:
    database:
    